name: Update JioTV Cookies

on:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours
  workflow_dispatch:

jobs:
  update-cookies:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      updated: ${{ steps.update.outputs.updated }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests tenacity

      - name: Update cookies in Zootv.json
        id: update
        run: |
          python - <<EOF
          import requests
          import json
          import re
          import os
          from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

          m3u_url = "https://raw.githubusercontent.com/alex8875/m3u/refs/heads/main/jstar.m3u"

          @retry(
              stop=stop_after_attempt(3),
              wait=wait_exponential(multiplier=1, min=4, max=10),
              retry=retry_if_exception_type(requests.RequestException)
          )
          def fetch_m3u():
              response = requests.get(m3u_url, timeout=10)
              response.raise_for_status()
              return response.text

          try:
              m3u_content = fetch_m3u()
          except requests.RequestException as e:
              print(f"Error fetching m3u: {e}")
              exit(1)

          # Extract __hdnea__ cookie
          cookie_match = re.search(r'__hdnea__=[^\s"\n;),]+', m3u_content)
          if not cookie_match:
              cookie_match = re.search(r'__hdnea__=[^"\n;]+', m3u_content)
          if not cookie_match:
              print("Error: No __hdnea__ cookie found")
              exit(1)

          new_cookie = cookie_match.group(0).rstrip(';').strip()
          print(f"Extracted cookie: {new_cookie}")

          json_file = "Zootv.json"
          if not os.path.exists(json_file):
              print(f"Error: {json_file} not found")
              exit(1)

          # Read current JSON
          try:
              with open(json_file, 'r') as f:
                  data = json.load(f)
          except json.JSONDecodeError as e:
              print(f"Invalid JSON: {e}")
              exit(1)

          # Check if update is needed
          updated = False
          if isinstance(data, list):
              for i, item in enumerate(data):
                  if isinstance(item, dict) and item.get("cookie") != new_cookie:
                      print(f"Updating item {i}: {item.get('name', 'unknown')}")
                      item["cookie"] = new_cookie
                      updated = True
          elif isinstance(data, dict):
              if data.get("cookie") != new_cookie:
                  print(f"Updating root cookie")
                  data["cookie"] = new_cookie
                  updated = True
          else:
              print("Error: Invalid Zootv.json structure")
              exit(1)

          if not updated:
              print("No changes needed")
              echo "updated=false" >> $GITHUB_OUTPUT
              exit(0)

          # Write updated JSON
          with open(json_file, 'w') as f:
              json.dump(data, f, indent=2)
              f.write('\n')
          print("Zootv.json updated")

          echo "updated=true" >> $GITHUB_OUTPUT
          EOF

      # Only commit and push if changes were made
      - name: Commit and push if updated
        if: steps.update.outputs.updated == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Zootv.json
          git commit -m "Auto-update JioTV cookie [$(date -u '+%Y-%m-%d %H:%M UTC')]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Notify if no update
      - name: No changes detected
        if: steps.update.outputs.updated != 'true'
        run: echo "No cookie update needed. Skipping commit."
